# Generated by Django 2.1.2 on 2018-10-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='pranav', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
